# -*- coding: utf-8 -*-
"""Stock Market Predictor Final2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7PBt7nmaTKY0ItDKl6-2pRp9D3LfoxI
"""

# =========================
# CELL 1: INSTALL + IMPORTS
# =========================
!pip -q install yfinance ipywidgets

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

import ipywidgets as widgets
from IPython.display import display, clear_output

plt.rcParams["figure.figsize"] = (12, 5)
print("TensorFlow:", tf.__version__)

# ==========================================
# CELL 2: DATA FETCH + INDICATORS (ROBUST)
# ==========================================
def fetch_ohlcv(ticker: str, start: str, end: str, interval: str = "1d") -> pd.DataFrame:
    df = yf.download(
        ticker,
        start=start,
        end=end,
        interval=interval,
        progress=False,
        auto_adjust=False,
        group_by="column",
    )

    if df is None or df.empty:
        raise ValueError("No data returned. Check ticker/date range.")

    # Handle MultiIndex columns robustly
    if isinstance(df.columns, pd.MultiIndex):
        lvl0 = [str(c).strip() for c in df.columns.get_level_values(0)]
        lvl1 = [str(c).strip() for c in df.columns.get_level_values(1)]

        # If OHLC names exist in level 0, keep level 0; else use level 1
        if "Close" in lvl0 or "Adj Close" in lvl0:
            df.columns = lvl0
        else:
            df.columns = lvl1

    # Normalize names
    df.columns = [str(c).strip() for c in df.columns]
    name_map = {
        "open": "Open",
        "high": "High",
        "low": "Low",
        "close": "Close",
        "adj close": "Adj Close",
        "volume": "Volume",
    }
    df = df.rename(columns={c: name_map.get(c.lower(), c) for c in df.columns})

    # Ensure Close exists
    if "Close" not in df.columns:
        if "Adj Close" in df.columns:
            df["Close"] = df["Adj Close"]
        else:
            raise ValueError(f"'Close' not found. Columns: {list(df.columns)}")

    # Force numeric where possible
    for c in df.columns:
        df[c] = pd.to_numeric(df[c], errors="ignore")

    df = df.dropna()
    df.index = pd.to_datetime(df.index)
    return df


def add_indicators_from_close(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    if "Close" not in out.columns:
        raise ValueError(f"'Close' missing. Available columns: {list(out.columns)}")

    close = out["Close"]
    if isinstance(close, pd.DataFrame):  # safety for duplicate close columns
        close = close.iloc[:, 0]
    close = pd.to_numeric(close, errors="coerce")

    # Returns
    out["pct_return"] = close.pct_change()
    out["log_return"] = np.log(close).diff()

    # Trend
    out["sma10"] = close.rolling(10).mean()
    out["sma20"] = close.rolling(20).mean()
    out["ema10"] = close.ewm(span=10, adjust=False).mean()
    out["ema20"] = close.ewm(span=20, adjust=False).mean()
    out["ema50"] = close.ewm(span=50, adjust=False).mean()

    # Volatility
    out["vol20"] = out["pct_return"].rolling(20).std()

    # RSI(14)
    delta = close.diff()
    gain = delta.clip(lower=0)
    loss = (-delta).clip(lower=0)
    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()
    rs = avg_gain / (avg_loss + 1e-9)
    out["rsi14"] = 100 - (100 / (1 + rs))

    # MACD(12,26,9)
    ema12 = close.ewm(span=12, adjust=False).mean()
    ema26 = close.ewm(span=26, adjust=False).mean()
    out["macd"] = ema12 - ema26
    out["macd_signal"] = out["macd"].ewm(span=9, adjust=False).mean()
    out["macd_hist"] = out["macd"] - out["macd_signal"]

    # Bollinger(20,2)
    bb_mid = close.rolling(20).mean()
    bb_std = close.rolling(20).std()
    out["bb_mid"] = bb_mid
    out["bb_upper"] = bb_mid + 2 * bb_std
    out["bb_lower"] = bb_mid - 2 * bb_std
    out["bb_width"] = (out["bb_upper"] - out["bb_lower"]) / (bb_mid + 1e-9)

    # Calendar
    out["dayofweek"] = out.index.dayofweek

    out = out.replace([np.inf, -np.inf], np.nan)
    return out

# ======================================
# CELL 3: WINDOWING + MODEL + FORECAST
# ======================================
def make_windows_multifeat(X_scaled: np.ndarray, y_scaled: np.ndarray, lookback: int):
    Xw, yw = [], []
    for i in range(lookback, len(X_scaled)):
        Xw.append(X_scaled[i - lookback:i, :])
        yw.append(y_scaled[i, 0])
    return np.array(Xw), np.array(yw).reshape(-1, 1)


def train_val_split_time(X, y, val_ratio=0.2):
    n = len(X)
    split = int(n * (1 - val_ratio))
    return X[:split], y[:split], X[split:], y[split:]


def build_gru(lookback: int, n_features: int, units=64, dropout=0.2, lr=1e-3):
    model = keras.Sequential([
        layers.Input(shape=(lookback, n_features)),
        layers.GRU(units, return_sequences=True),
        layers.Dropout(dropout),
        layers.GRU(units),
        layers.Dropout(dropout),
        layers.Dense(64, activation="relu"),
        layers.Dense(1),
    ])
    model.compile(optimizer=keras.optimizers.Adam(lr), loss="mse")
    return model


def plot_actual_vs_pred(dates, actual, pred, title):
    plt.figure()
    plt.plot(dates, actual, label="Actual", linewidth=2)
    plt.plot(dates, pred, label="Predicted", linewidth=2)
    plt.title(title)
    plt.xlabel("Date")
    plt.ylabel("Close")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.show()


def forecast_future_close_iterative(
    model,
    close_history: pd.DataFrame,   # index datetime, col Close
    feature_cols,
    lookback: int,
    steps: int,
    feature_scaler: MinMaxScaler,
    target_scaler: MinMaxScaler,
):
    tmp = close_history[["Close"]].copy().sort_index()
    preds = []
    f_dates = []
    last_date = tmp.index[-1]

    for _ in range(steps):
        feats = add_indicators_from_close(tmp)
        feats = feats[feature_cols + ["Close"]].dropna()

        x_window = feats.iloc[-lookback:][feature_cols].values
        x_scaled = feature_scaler.transform(x_window).reshape(1, lookback, len(feature_cols))

        pred_scaled = model.predict(x_scaled, verbose=0)[0, 0]
        pred_close = target_scaler.inverse_transform([[pred_scaled]])[0, 0]

        next_date = last_date + pd.tseries.offsets.BDay(1)
        tmp.loc[next_date, "Close"] = float(pred_close)

        preds.append(float(pred_close))
        f_dates.append(next_date)
        last_date = next_date

    return np.array(preds), pd.DatetimeIndex(f_dates)

# ===================================
# CELL 4: INTERACTIVE COLAB WIDGETS
# ===================================
ticker_w = widgets.Text(value="RELIANCE.NS", description="Ticker:", layout=widgets.Layout(width="320px"))
start_w  = widgets.Text(value="2016-01-01", description="Start:", layout=widgets.Layout(width="320px"))
end_w    = widgets.Text(value=pd.Timestamp.today().strftime("%Y-%m-%d"), description="End:", layout=widgets.Layout(width="320px"))

lookback_w = widgets.IntSlider(value=80, min=30, max=250, step=5, description="Lookback:")
epochs_w   = widgets.IntSlider(value=20, min=3, max=120, step=1, description="Epochs:")
batch_w    = widgets.IntSlider(value=64, min=16, max=256, step=16, description="Batch:")
units_w    = widgets.IntSlider(value=64, min=16, max=256, step=16, description="Units:")
dropout_w  = widgets.FloatSlider(value=0.2, min=0.0, max=0.6, step=0.05, description="Dropout:")
val_w      = widgets.FloatSlider(value=0.2, min=0.1, max=0.4, step=0.05, description="Val ratio:")
horizon_w  = widgets.IntSlider(value=10, min=1, max=60, step=1, description="Forecast days:")

run_btn = widgets.Button(description="Run (Live Download -> Train -> Forecast)", button_style="primary")
out = widgets.Output()

display(widgets.VBox([
    widgets.HBox([ticker_w, start_w, end_w]),
    widgets.HBox([lookback_w, epochs_w, batch_w]),
    widgets.HBox([units_w, dropout_w, val_w]),
    widgets.HBox([horizon_w]),
    run_btn,
    out
]))

# ==========================
# CELL 5: RUN BUTTON LOGIC
# ==========================
def on_run(_):
    with out:
        clear_output(wait=True)
        try:
            ticker = ticker_w.value.strip().upper()
            start  = start_w.value.strip()
            end    = end_w.value.strip()
            lookback = int(lookback_w.value)
            epochs   = int(epochs_w.value)
            batch    = int(batch_w.value)
            units    = int(units_w.value)
            dropout  = float(dropout_w.value)
            val_ratio = float(val_w.value)
            horizon  = int(horizon_w.value)

            print(f"Downloading latest data for {ticker} ...")
            df = fetch_ohlcv(ticker, start, end)

            # Add indicators
            df_ind = add_indicators_from_close(df)

            # Feature set
            feature_cols = [
                "pct_return", "log_return",
                "sma10", "sma20", "ema10", "ema20", "ema50",
                "vol20",
                "rsi14",
                "macd", "macd_signal", "macd_hist",
                "bb_mid", "bb_upper", "bb_lower", "bb_width",
                "dayofweek"
            ]

            # Keep needed cols and drop initial NaN rows from rolling calculations
            df_ind = df_ind[feature_cols + ["Close"]].dropna()

            if len(df_ind) < (lookback + 80):
                raise ValueError(
                    f"Not enough rows after indicators ({len(df_ind)}). "
                    f"Use earlier start date or reduce lookback."
                )

            # Time split index (also used for scaler fit to reduce leakage)
            split_row = int(len(df_ind) * (1 - val_ratio))
            train_part = df_ind.iloc[:split_row]

            feature_scaler = MinMaxScaler()
            target_scaler = MinMaxScaler()
            feature_scaler.fit(train_part[feature_cols].values)
            target_scaler.fit(train_part[["Close"]].values)

            X_all = feature_scaler.transform(df_ind[feature_cols].values)
            y_all = target_scaler.transform(df_ind[["Close"]].values)

            X, y = make_windows_multifeat(X_all, y_all, lookback)
            X_train, y_train, X_val, y_val = train_val_split_time(X, y, val_ratio=val_ratio)

            model = build_gru(
                lookback=lookback,
                n_features=len(feature_cols),
                units=units,
                dropout=dropout,
                lr=1e-3
            )

            callbacks = [
                keras.callbacks.EarlyStopping(monitor="val_loss", patience=8, restore_best_weights=True),
                keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=4, min_lr=1e-5),
            ]

            print("Training model ...")
            hist = model.fit(
                X_train, y_train,
                validation_data=(X_val, y_val),
                epochs=epochs,
                batch_size=batch,
                verbose=0,
                callbacks=callbacks
            )

            # Loss curve
            plt.figure(figsize=(12, 4))
            plt.plot(hist.history["loss"], label="train")
            plt.plot(hist.history["val_loss"], label="val")
            plt.title("Training Loss (MSE)")
            plt.xlabel("Epoch")
            plt.ylabel("MSE")
            plt.grid(True, alpha=0.3)
            plt.legend()
            plt.show()

            # Validation predictions (back to price space)
            y_val_pred_scaled = model.predict(X_val, verbose=0).ravel()
            y_val_true_scaled = y_val.ravel()

            y_val_pred = target_scaler.inverse_transform(y_val_pred_scaled.reshape(-1, 1)).ravel()
            y_val_true = target_scaler.inverse_transform(y_val_true_scaled.reshape(-1, 1)).ravel()

            mae = mean_absolute_error(y_val_true, y_val_pred)
            rmse = np.sqrt(mean_squared_error(y_val_true, y_val_pred))
            print(f"Validation MAE: {mae:.2f}")
            print(f"Validation RMSE: {rmse:.2f}")

            # Dates for validation targets
            target_dates = df_ind.index[lookback:]     # one date per y
            val_dates = target_dates[len(y_train):]    # validation segment
            plot_actual_vs_pred(val_dates, y_val_true, y_val_pred, f"{ticker} Validation: Actual vs Predicted")

            # Future forecast
            close_history = df_ind[["Close"]].copy()
            future_prices, future_dates = forecast_future_close_iterative(
                model=model,
                close_history=close_history,
                feature_cols=feature_cols,
                lookback=lookback,
                steps=horizon,
                feature_scaler=feature_scaler,
                target_scaler=target_scaler,
            )

            # Plot history + forecast
            tail_n = min(250, len(df_ind))
            plt.figure()
            plt.plot(df_ind.index[-tail_n:], df_ind["Close"].values[-tail_n:], label="Historical Close", linewidth=2)
            plt.plot(future_dates, future_prices, label=f"Forecast (+{horizon} business days)", linewidth=2)
            plt.title(f"{ticker} Forecast")
            plt.xlabel("Date")
            plt.ylabel("Close")
            plt.grid(True, alpha=0.3)
            plt.legend()
            plt.show()

            forecast_df = pd.DataFrame({"Date": future_dates, "PredictedClose": future_prices})
            display(forecast_df)

            print("\nDone. Change ticker/settings and click Run again.")

        except Exception as e:
            print("Error:", str(e))


run_btn.on_click(on_run)
print("Ready. Click the Run button above.")

!pip install streamlit
import streamlit as st
import numpy as np
import pandas as pd
import yfinance as yf
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import tensorflow as tf
from tensorflow.keras import layers, Sequential

st.set_page_config(page_title="Indian Stock Predictor", layout="wide")
st.title("Indian Stock Price Predictor (NSE/BSE)")

ticker = st.text_input("Ticker", "RELIANCE.NS")
start = st.date_input("Start date", pd.to_datetime("2018-01-01"))
end = st.date_input("End date", pd.to_datetime("today"))
lookback = st.slider("Lookback", 30, 180, 60, 5)
epochs = st.slider("Epochs", 3, 50, 10, 1)
horizon = st.slider("Forecast days", 1, 30, 7, 1)

@st.cache_data(ttl=900)
def fetch_data(ticker, start, end):
    df = yf.download(ticker, start=str(start), end=str(end), progress=False, auto_adjust=False)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    if "Close" not in df.columns and "Adj Close" in df.columns:
        df["Close"] = df["Adj Close"]
    return df.dropna()

def make_windows(arr, lb):
    X, y = [], []
    for i in range(lb, len(arr)):
        X.append(arr[i-lb:i, 0])
        y.append(arr[i, 0])
    return np.array(X).reshape(-1, lb, 1), np.array(y).reshape(-1, 1)

if st.button("Run"):
    df = fetch_data(ticker, start, end)
    if df.empty or "Close" not in df.columns:
        st.error("No data / Close not found")
        st.stop()

    close = df[["Close"]].astype(float)
    scaler = MinMaxScaler()
    s = scaler.fit_transform(close.values)

    X, y = make_windows(s, lookback)
    split = int(len(X) * 0.8)
    X_train, y_train = X[:split], y[:split]
    X_val, y_val = X[split:], y[split:]

    model = Sequential([
        layers.Input(shape=(lookback, 1)),
        layers.GRU(32, return_sequences=True),
        layers.GRU(32),
        layers.Dense(1)
    ])
    model.compile(optimizer="adam", loss="mse")
    model.fit(X_train, y_train, validation_data=(X_val, y_val), epochs=epochs, batch_size=64, verbose=0)

    pred = model.predict(X_val, verbose=0)
    y_true = scaler.inverse_transform(y_val).ravel()
    y_pred = scaler.inverse_transform(pred).ravel()

    mae = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    st.write(f"MAE: {mae:.2f} | RMSE: {rmse:.2f}")

    chart_df = pd.DataFrame({"Actual": y_true, "Predicted": y_pred})
    st.line_chart(chart_df)

    # iterative forecast
    win = s[-lookback:].copy()
    fut = []
    for _ in range(horizon):
        p = model.predict(win.reshape(1, lookback, 1), verbose=0)[0,0]
        fut.append(p)
        win = np.vstack([win[1:], [[p]]])

    fut_price = scaler.inverse_transform(np.array(fut).reshape(-1,1)).ravel()
    st.subheader("Future forecast")
    st.dataframe(pd.DataFrame({"Day": np.arange(1, horizon+1), "PredictedClose": fut_price}))